apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: user-service
    version: {{ .Chart.AppVersion | default "1.0" }}
data:
  application.yml: |
    server:
      port: {{ .Values.config.server.port | default 8080 }}
    spring:
      application:
        name: {{ .Values.config.app.name | default "dashboard-service" }}
      cloud:
        kubernetes:
          discovery:
            enabled: true
            discovery-server-url: https://kubernetes.default.svc  # 쿠버네티스 API Server 주소
            all-namespaces: true      # 다른 네임스페이스의 서비스도 찾기
            include-not-ready-addresses: false  # 준비된 Pod만 포함
          client:
            namespace: dashboard-service
    management:
      endpoints:
        web:
          exposure:
            include: "*"
    aws:
      region: ${AWS_REGGION}
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}