apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: user-service
    version: {{ .Chart.AppVersion | default "1.0" }}
data:
  application.yml: |
    server:
      port: {{ .Values.config.server.port | default 8080 }}
    spring:
      application:
        name: {{ .Values.config.app.name | default "dashboard-service" }}
    management:
      endpoints:
        web:
          exposure:
            include: "*"
    aws:
      region: ${AWS_REGGION}
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}