replicaCount: 1

image:
  repository: 026274465258.dkr.ecr.ap-northeast-2.amazonaws.com/dashboard-service
  tag: 20250613-445d675
  pullPolicy: IfNotPresent    # 이미지 가져오는 정책 로컬에 없을 때만 pull

service:
  type: ClusterIP   # 클러스터 내부에서만 접근 가능 (기본값)
  port: 80

# 헬스체크 설정 (권장)
healthCheck:
  enabled: true
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 120
  periodSeconds: 10

# Dashboard Service Config
config:
  server:
    port: 8080
  app:
    name: dashboard-service
  service:
    llm:
      url: http://llm-service.llm-service.svc.cluster.local:80
    report:
      url: http://agent-service.agent-service.svc.cluster.local:80
    reward:
      url: http://reward-service.reward-service.svc.cluster.local:80
    user:
      url: http://user-service.user-service.svc.cluster.local:80